### ISSUE TITLE
run into an error on iOS 14

### ISSUE THREAD

**Issue by 349989153** [vbanurag/rn-media-meta#3]
Hello，I use this project together with `react-native-image-picker` to select a video file，and got error on iOS 14 simulator：

**[Error: 未能完成操作。（file not found错误-15。）]**

among that，the file data I get from `react-native-image-picker` is just like：

```json
{
  "fileName": "362d7052-b547-42f3-b474-9a69f1355cd8.mp4", 
  "origURL": "assets-library://asset/asset.MP4?id=0A91C004-732E-4A67-A367-DD8F6EB36FA8&ext=MP4", 
  "timestamp": "2020-10-09T20:10:08Z", 
  "uri": "file:///Users/luyang/Library/Developer/CoreSimulator/Devices/1D9CF54F-381F-4D5A-A212-AA278F152936/data/Containers/Data/Application/8AC63AD3-B061-4A57-AC9C-8EC3F4391712/tmp/trim.7E8C32C5-0033-43FA-8BE8-BD500913D6B1.MOV"
}
```

However, not matter I use `fileName` or `origUrl` or `uri`, it doesnt work and end up with the error I post above, can you help me , thanks

**Comment by 349989153** [comment]
Ok, I SOLVED this by using `MediaMeta.get(uri.replace('file://', ''))`, just remove `file://`

**Comment by vbanurag** [comment]
create PR
